# Task 1 – works on the Serper news snippets already passed in via `inputs`.

find_trending_companies:
  description: >
    Using the provided **news_snippets** for {sector}, identify 2-3 companies that are
    currently trending and have not been selected before.
  expected_output: >
    JSON list of objects with company name, ticker, and why it is trending.
  agent: trending_company_finder
  output_file: output/trending_companies.json


# Task 2 – research each company found in Task 1.

research_trending_companies:
  description: >
    For each company in the trending list, deliver a detailed analysis covering
    market position, future outlook, and investment potential. Use open-source
    information (reports, websites, filings, etc.) but do NOT perform additional
    live web searches; rely on your internal knowledge and the supplied data.
  expected_output: >
    A JSON or Markdown report with a section per company.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json


# Task 3 – pick the single best company.

pick_best_company:
  description: >
    Evaluate the research findings and pick the best company for investment.
    Respond with a short “push notification”-style sentence announcing the pick,
    followed by a detailed rationale. Also list the companies you rejected and why.
  expected_output: >
    A Markdown file containing:
      * Chosen company and 1-sentence rationale
      * Full explanation (≈1–2 paragraphs)
      * Brief notes on companies not selected
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
